name: flutter_ionicons
description: "A new Flutter package project."
version: 0.0.1
homepage:

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

  icon_font_generator:
    git: https://github.com/stongef-sonepar/icon_font_generator.git
  
flutter:
  fonts:
    - family: Ionicons
      fonts:
        - asset: lib/font/ionicons.otf